### ISSUE TITLE
Add 404 (not found) page

### ISSUE THREAD

**Issue by BossBele** [LarvenLLC/larven#18]
Add a customized, cool and coorporate 404 page

**Comment by BossBele** [comment]
@chibokocl  please provide @babjonii  with a sample/template or design for this

**Comment by chibokocl** [comment]
For what?

**Comment by BossBele** [comment]
Hii ni page inayokuja mtu akiwa amejaribu kufungua page ambayo haipo.

Yaani amepatia domain ila kakosea url (link). Eg: www.larven.co.tz/silicon-dar

Kwasas page inayokuja ni ya firebase lakini ni vizuri tukiweka yetu.

**Comment by BossBele** [comment]
You don't have to design it, ila kama una recommendations, tupatie. Kama hauna, tutaweka what feels right

**Comment by chibokocl** [comment]
You mean 404 bad gateway?

**Comment by chibokocl** [comment]
I am designing it

**Comment by chibokocl** [comment]
![404](https://user-images.githubusercontent.com/93471316/142184702-8fa33788-f1cd-438a-87f2-10eeea39e2e7.png)
@BossBele @babjonii Design yenu io hapo

**Comment by BossBele** [comment]
@chibokocl it is a great design. @babjonii panapopatikana nafasi tunaomba supana ihusike

**Comment by BossBele** [comment]
@babjonii may I call this to your attention

**Comment by babjonii** [comment]
How can I get the 404 image?

**Comment by BossBele** [comment]
![image](https://user-images.githubusercontent.com/28963165/152524092-691f75ea-b56e-4594-b8e8-98eda33420f1.png)


@babjonii

**Comment by BossBele** [comment]
![0232fdb23f142b8cc83edcaf3c35c402-removebg-preview](https://user-images.githubusercontent.com/28963165/152524435-1299a87a-717d-4443-847f-de7b0b07310b.png)

@babjonii

**Comment by BossBele** [comment]
![152524435-1299a87a-717d-4443-847f-de7b0b07310b (1)](https://user-images.githubusercontent.com/28963165/152854079-8cc8f5af-1cae-4800-bc0d-160124666fef.png)
