### ISSUE TITLE
Resize Homepage Animation Images to improve website performance

### ISSUE THREAD

**Issue by BossBele** [LarvenLLC/larven#38]
![Screenshot from 2022-02-15 21-00-42](https://user-images.githubusercontent.com/28963165/154121530-37f4f3fc-d6b4-4b06-982e-9a7a3818b2d5.png)

The images are currently too large (1000px)
They both need to be resized to 320px X 320px (height X width).
Please maintain transparency.
@babjonii

**Comment by babjonii** [comment]
Done
